### ISSUE TITLE
rez-pip cannot install astroid for python version 2

### ISSUE THREAD

**Issue by ColinKennedy** [nerdvegas/rez#1262]
Describe the bug here.

Calling `rez-pip --install astroid --python-version=2 --release` fails with this traceback

```
08:30:52 INFO     Trying to use pip from python package
08:30:52 INFO     Found pip-20.0.2 inside /home/selecaoone/packages/python/2.7.5/package.py. Will use it via /home/selecaoone/packages/python/2.7.5/platform-linux/arch-x86_64/os-CentOS-7.9.2009/bin/python
08:30:52 INFO     Installing 'astroid' with pip taken from '/home/selecaoone/packages/python/2.7.5/platform-linux/arch-x86_64/os-CentOS-7.9.2009/bin/python'
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting astroid
  Using cached https://files.pythonhosted.org/packages/8b/29/0f7ec6fbf28a158886b7de49aee3a77a8a47a7e24c60e9fd6ec98ee2ec02/astroid-1.6.6-py2.py3-none-any.whl
Collecting enum34>=1.1.3; python_version < "3.4" (from astroid)
  Using cached https://files.pythonhosted.org/packages/6f/2c/a9386903ece2ea85e9807e0e062174dc26fdce8b05f216d00491be29fad5/enum34-1.1.10-py2-none-any.whl
Collecting wrapt (from astroid)
  Using cached https://files.pythonhosted.org/packages/16/fb/6b426c8753bd2233309f24e7363461a95c7c374c435aa88c6ee9d0c7361f/wrapt-1.14.0-cp27-cp27mu-manylinux2010_x86_64.whl
Collecting singledispatch; python_version < "3.4" (from astroid)
  Using cached https://files.pythonhosted.org/packages/3f/09/2a17c6505a8373229cb3de6161e3af74ff90afcf4516719aa6cf32fad151/singledispatch-3.7.0-py2.py3-none-any.whl
Collecting backports.functools-lru-cache; python_version < "3.4" (from astroid)
  Using cached https://files.pythonhosted.org/packages/e5/c1/1a48a4bb9b515480d6c666977eeca9243be9fa9e6fb5a34be0ad9627f737/backports.functools_lru_cache-1.6.4-py2.py3-none-any.whl
Collecting lazy-object-proxy (from astroid)
  Using cached https://files.pythonhosted.org/packages/6f/3e/7c80e8536b9d5eb66e784fff4c359adf9e55b37460fd6928192256ba71f2/lazy-object-proxy-1.7.0.tar.gz
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Complete output from command /home/selecaoone/packages/python/2.7.5/platform-linux/arch-x86_64/os-CentOS-7.9.2009/bin/python /home/selecaoone/packages/python/2.7.5/platform-linux/arch-x86_64/os-CentOS-7.9.2009/python/extra/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpri2VbD:
    ERROR: running dist_info
    creating /tmp/pip-install-7G1NF8/lazy-object-proxy/pip-wheel-metadata/lazy_object_proxy.egg-info
    writing /tmp/pip-install-7G1NF8/lazy-object-proxy/pip-wheel-metadata/lazy_object_proxy.egg-info/PKG-INFO
    writing top-level names to /tmp/pip-install-7G1NF8/lazy-object-proxy/pip-wheel-metadata/lazy_object_proxy.egg-info/top_level.txt
    writing dependency_links to /tmp/pip-install-7G1NF8/lazy-object-proxy/pip-wheel-metadata/lazy_object_proxy.egg-info/dependency_links.txt
    writing manifest file '/tmp/pip-install-7G1NF8/lazy-object-proxy/pip-wheel-metadata/lazy_object_proxy.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "/home/selecaoone/packages/python/2.7.5/platform-linux/arch-x86_64/os-CentOS-7.9.2009/python/extra/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "/home/selecaoone/packages/python/2.7.5/platform-linux/arch-x86_64/os-CentOS-7.9.2009/python/extra/pip/_vendor/pep517/_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/selecaoone/packages/python/2.7.5/platform-linux/arch-x86_64/os-CentOS-7.9.2009/python/extra/pip/_vendor/pep517/_in_process.py", line 69, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-LDXPYp/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 156, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-LDXPYp/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 243, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/tmp/pip-build-env-LDXPYp/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 146, in <module>
        distclass=BinaryDistribution,
      File "/tmp/pip-build-env-LDXPYp/overlay/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-LDXPYp/overlay/lib/python2.7/site-packages/setuptools/command/dist_info.py", line 31, in run
        egg_info.run()
      File "/tmp/pip-build-env-LDXPYp/overlay/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 296, in run
        self.find_sources()
      File "/tmp/pip-build-env-LDXPYp/overlay/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
        mm.run()
      File "/tmp/pip-build-env-LDXPYp/overlay/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 534, in run
        self.add_defaults()
      File "/tmp/pip-build-env-LDXPYp/overlay/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
        sdist.add_defaults(self)
      File "/tmp/pip-build-env-LDXPYp/overlay/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
        self._add_defaults_ext()
      File "/tmp/pip-build-env-LDXPYp/overlay/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 118, in _add_defaults_ext
        if self.distribution.has_ext_modules():
      File "setup.py", line 70, in has_ext_modules
        return super().has_ext_modules() or 'SETUP_PY_ALLOW_PURE' not in os.environ
    TypeError: super() takes at least 1 argument (0 given)
    ----------------------------------------
ERROR: Command "/home/selecaoone/packages/python/2.7.5/platform-linux/arch-x86_64/os-CentOS-7.9.2009/bin/python /home/selecaoone/packages/python/2.7.5/platform-linux/arch-x86_64/os-CentOS-7.9.2009/python/extra/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpri2VbD" failed with error code 1 in /tmp/pip-install-7G1NF8/lazy-object-proxy
WARNING: You are using pip version 19.1.1, however version 20.3.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
08:30:57 ERROR    BuildError: Failed to download source with pip: /home/selecaoone/packages/python/2.7.5/platform-linux/arch-x86_64/os-CentOS-7.9.2009/bin/python -m pip install --use-pep517 --target=/tmp/pip-hc5023gx-rez astroid
```

**Environment**
* OS (eg "linux ubuntu 18.04") - CentOS Linux release 7.9.2009 (Core)
* Rez version (eg "2.100.0") - 2.105.0
* Rez python version (output of "rez-python --version") - Python 3.6.8

**To Reproduce**
(Make sure you `rez-bind python --exe `/path/to/python-2.7/bin/python` first)

- Call `rez-pip --install astroid --python-version=2 --release`
- Alternative: call `rez-pip --install astroid==1.6.6 --python-version=2 --release` if you want an explicit version

**Expected behavior**
astroid should have installed to the release_packages_path

**Actual behavior**
It fails instead

Note:

- `rez-pip --install astroid --python-version=3 --release` works.
- I retried the production steps using Rez 2.105.0 installed with a matching Python 2.7 version with what I have via rez-bind. Same error.

**Comment by JeanChristopheMorinPerso** [comment]
I don't think this is a bug with rez-pip itself.

I would try to run:
```
/home/selecaoone/packages/python/2.7.5/platform-linux/arch-x86_64/os-CentOS-7.9.2009/bin/python -m pip install --target <path to a custom folder>
```

I have a feeling you will get the same error.

**Comment by ColinKennedy** [comment]
I ran `python -m pip install astroid==1.6.6 --target /tmp/output_1 --use-pep517` and it works

```
selecaoone@SelecaoOne:~$ python -m pip install astroid==1.6.6 --target /tmp/output_1 --use-pep517
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is
no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support i
n pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove
 support for this functionality.
Collecting astroid==1.6.6
  Using cached astroid-1.6.6-py2.py3-none-any.whl (305 kB)
Collecting enum34>=1.1.3; python_version < "3.4"
  Using cached enum34-1.1.10-py2-none-any.whl (11 kB)
Collecting singledispatch; python_version < "3.4"
  Using cached singledispatch-3.7.0-py2.py3-none-any.whl (9.2 kB)
Collecting backports.functools-lru-cache; python_version < "3.4"
  Using cached backports.functools_lru_cache-1.6.4-py2.py3-none-any.whl (5.9 kB)
Collecting wrapt
  Using cached wrapt-1.14.0-cp27-cp27mu-manylinux2010_x86_64.whl (75 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting lazy-object-proxy
  Downloading lazy_object_proxy-1.6.0-cp27-cp27mu-manylinux1_x86_64.whl (53 kB)
     |████████████████████████████████| 53 kB 1.1 MB/s
Installing collected packages: enum34, six, singledispatch, backports.functools-lru-cache, wrapt, lazy-object-proxy, a
stroid
ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages. This behaviour
 is the source of the following dependency conflicts.
rtslib-fb 2.1.74 requires pyudev>=0.16.1, but you'll have pyudev 0.15 which is incompatible.
ipapython 4.6.8 requires dnspython>=1.15, but you'll have dnspython 1.12.0 which is incompatible.
ipapython 4.6.8 requires python-ldap>=3.0.0b1, but you'll have python-ldap 2.4.15 which is incompatible.
Successfully installed astroid-1.6.6 backports.functools-lru-cache-1.6.4 enum34-1.1.10 lazy-object-proxy-1.6.0 singled
ispatch-3.7.0 six-1.16.0 wrapt-1.14.0
selecaoone@SelecaoOne:~$
```

Granted there's a few pip errors towards the end. But the package does install.

**Comment by JeanChristopheMorinPerso** [comment]
In your initial error, `lazy_object_proxy` is being built from source (sdist) (**version 1.7.0**, which was yanked in PyPI) while in your second error, it's downloading a wheel from version **1.6.0** and installing it.

So first is the version mismatch between the two errors. This is a big red-herring. `lazy_object_proxy` 1.7.0 dropped support for Python 2.7 but they forgot to change their `python_requires` to really stop any Python 2.7 version to install 1.7. So they yanked it and released 1.7.1 with the `python_requires` fix.

The fact that we see `Collecting singledispatch; python_version < "3.4" (from astroid)` in your first error confirms that it's effectively installing from Python 2.7.

And we can clearly see in the logs that `lazy-object-proxy` isn't pinned to 1.7.0. Yanking support was added in Pip 19.2. So what this means is that the pip version used between the two errors differ and might be the source of your problem.

Do you happen to have pip installed in your `~/.local/lib/python2.7` directory? Is pip from your rez package the same as the system one (since you rez-binded python)?

**Comment by JeanChristopheMorinPerso** [comment]
Also, there is another red flag:

```
      File "/tmp/pip-build-env-LDXPYp/overlay/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
```

See, setuptools comes from your rezified python package while distutils comes from your system python.

**Comment by ColinKennedy** [comment]
I'm no longer able to reproduce this and judging from feedback, it was user error. Closing this one.

**Comment by bpabel** [comment]
Yeah, this is really a problem with pip pulling src dists for distributions that don't support python 2.7. You can tell pip to only pull binary distributions (`whl`'s) for certain dependencies to sidestep this error. 

```
pip install astroid==1.6.6 --only-binary lazy-object-proxy
```

You can pass those extra pip args to `rez-pip` with the `-e/--extra` option

```
rez-pip -i --python-version 2.7 astroid==1.6.6 -e --only-binary lazy-object-proxy
```
