### ISSUE TITLE
rez config failes with AttributeError

### ISSUE THREAD

**Issue by sebastianelsner** [nerdvegas/rez#183]
rez config
Traceback (most recent call last):
  File "/raid/standards/base-setups/rez/bin/rez/rez", line 4, in <module>
    run()
  File "/raid/standards/base-setups/rez/lib/python2.6/site-packages/rez-2.0.BETA.30-py2.6.egg/rez/cli/_main.py", line 107, in run
    returncode = opts.func(opts, opts.parser, arg_groups[1:])
  File "/raid/standards/base-setups/rez/lib/python2.6/site-packages/rez-2.0.BETA.30-py2.6.egg/rez/cli/config.py", line 20, in command
    data = config.data
  File "/raid/standards/base-setups/rez/lib/python2.6/site-packages/rez-2.0.BETA.30-py2.6.egg/rez/config.py", line 374, in data
    d[key] = getattr(self, key)
AttributeError: 'Config' object has no attribute 'resource_caching'

**Comment by sebastianelsner** [comment]
this is from resources2 branch with python 2.6 on centos 6.6. Would it be a good idea to use
getattr(self, key, None) or add a try: .. except:... ?

**Comment by nerdvegas** [comment]
This might be related to a recent merge, something the UTs didn't pick up.. I'll have a look

**Comment by nerdvegas** [comment]
fixed in resources2.
