### ISSUE TITLE
rez-env fails when supplying inclusion filter

### ISSUE THREAD

**Issue by nerdvegas** [nerdvegas/rez#209]
]$ rez-env foo --include foo
  File "/tools/share/venvs/rez/2.0.rc1.16/local/lib/python2.7/site-packages/rez-2.0.rc1.16-py2.7.egg/rez/package_filter.py", line 245, in add_inclusion
    self.filters = [(x + f) for x in self.filters]
TypeError: unsupported operand type(s) for +: 'PackageFilter' and 'PackageFilter'

**Comment by mstreatfield** [comment]
I *think* this bug has changed since it was originally reported.  `rez env` no longer fails when supplying the inclusion filter:

    rez env foo --include "range(foo-1.0.2)" -c "echo foo"
    foo

However the filter has no effect unless there is an existing exclusion filter.  As `add_inclusion` is operating on the existing `self.filters` attribute of `PackageFilterList`, if there are no filters the inclusion is not added.  

With an exclusion filter I am then able to get the same traceback as reported here:

    rez env --exclude "after(1403596365)" foo --include "range(foo-1.0.2)" -c "echo foo"
    Traceback (most recent call last):
      File "/home/users/markst/packages/rez/2.0.rc1.16.0/CentOS-6.2_thru_7/python-2.7/bin/rez/rez", line 4, in <module>
        run()
      File "/fast/markst/packages/rez/2.0.rc1.16.0/CentOS-6.2_thru_7/python-2.7/lib/python2.7/site-packages/rez-2.0.rc1.16.0-py2.7.egg/rez/cli/_main.py", line 120, in run
        returncode = run_cmd()
      File "/fast/markst/packages/rez/2.0.rc1.16.0/CentOS-6.2_thru_7/python-2.7/lib/python2.7/site-packages/rez-2.0.rc1.16.0-py2.7.egg/rez/cli/_main.py", line 112, in run_cmd
        return opts.func(opts, opts.parser, arg_groups[1:])
      File "/fast/markst/packages/rez/2.0.rc1.16.0/CentOS-6.2_thru_7/python-2.7/lib/python2.7/site-packages/rez-2.0.rc1.16.0-py2.7.egg/rez/cli/env.py", line 185, in command
        package_filter.add_inclusion(rule)
      File "/fast/markst/packages/rez/2.0.rc1.16.0/CentOS-6.2_thru_7/python-2.7/lib/python2.7/site-packages/rez-2.0.rc1.16.0-py2.7.egg/rez/package_filter.py", line 245, in add_inclusion
        self.filters = [(x + f) for x in self.filters]
    TypeError: unsupported operand type(s) for +: 'PackageFilter' and 'PackageFilter'

Should it be possible to supply an inclusion filter without an exclusion filter?  Some of the code seems to concern itself only with exclusions which would prohibit this (e.g. this line in the solver):

    rule = self.package_filter.excludes(package)
    if rule:
        if config.debug_package_exclusions:
            print_debug("Package '%s' was excluded by rule '%s'" % (package.qualified_name, str(rule)))
        continue

**Comment by nerdvegas** [comment]
Hey Mark,

An inclusion filter only makes sense when added to an exclusion. I didn't think it very useful to support a whitelist on its own.

In other words, the behavior is always a blacklist, which then allows some packages back again in the whitelist. So, all beta packages are excluded for eg, except foo, because an inclusion for foo is added. An inclusion on its own is valid, but has no effect.

Hth
A

**Comment by mstreatfield** [comment]
Ok, I see.

With hindsight I also wonder if you have an exclusion filter configured in `rezconfig` and this is why we are getting different examples of the same problem, i.e you have a configured exclusion filter which is the same as my second example of specifying it on the command line.  In which case the bug hasn't changed, I just found a different way of triggering it...

**Comment by nerdvegas** [comment]
Yup that explanation sounds right. Yes we do have a default exclusion filters, ours is configured to exclude *.dev files.

I've since merged your recent PR fixing this, so closing.
