### ISSUE TITLE
python install.py output a strange error/stacktrace while install completes apparently successfully

### ISSUE THREAD

**Issue by gst** [nerdvegas/rez#398]
Hi,

using python2.7.13 (pythonz compiled) on centOS-6.7 on current master (2.9.1-1-g8c5b818),
(but anyway also having the same thing under other python or OS versions/flavors).

`python install.py destpath`

I'm getting at the end of the installation: 

```
Installed /home/gregory/rez/master-2.9.1/lib/python2.7/site-packages/rez-2.9.1-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 113, in <module>
    "Topic :: System :: Software Distribution"
  File "/opt/Pythons/CPython-2.7.13/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/Pythons/CPython-2.7.13/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/Pythons/CPython-2.7.13/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/gregory/rez/master-2.9.1/lib/python2.7/site-packages/setuptools/command/install.py", line 65, in run
    self.do_egg_install()
  File "/home/gregory/rez/master-2.9.1/lib/python2.7/site-packages/setuptools/command/install.py", line 115, in do_egg_install
    cmd.run()
  File "/home/gregory/rez/master-2.9.1/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 360, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/gregory/rez/master-2.9.1/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 576, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/gregory/rez/master-2.9.1/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 627, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/gregory/rez/master-2.9.1/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 677, in process_distribution
    distreq.project_name, distreq.specs, requirement.extras
TypeError: __init__() takes exactly 2 arguments (4 given)
```

I have not investigated more than that as it doesn't seem to impact anything (for now / with what I'm currently doing / testing).

but here is the report.

**Comment by nerdvegas** [comment]
Ouch, ok thanks. Maybe I should start on this platform-specific installer
soon then. I'd like to do away with this virtualenv-based installation.

A

**Comment by instinct-vfx** [comment]
@nerdvegas : Could you elaborate on "this platform specific installer" and "do away with this virtualenv-based installation"? I am in the progress of wrapping the installer and do some internal "magic" to parts of the installation. I would rather not work on things twice or create an deployment procedure that is bound to break soon.

**Comment by nerdvegas** [comment]
Well, rez is pure python, I'm hoping it's just a case of installing the
source and creating a bunch of wrapper scripts that do something like:

    #!/bin/bash
    # rez-env
    if [ -z "$_PRE_REZ_PYTHONPATH" ]; then  # will also do this for other
vars that might affect installation
        export _PRE_REZ_PYTHONPATH=$PYTHONPATH
    fi

    export PYTHONPATH=$_PRE_REZ_PYTHONPATH
    .rez env $@

The '.rez' tool would just be equivalent to current 'rez' tool (but hidden
because it's expected that some wrapper like above would use it).

Admittedly I haven't thought about this at length yet and I haven't tested
anything out.

A




On Thu, Mar 16, 2017 at 9:18 AM, Thorsten Kaufmann <notifications@github.com

**Comment by darkvertex** [comment]
Support for an easy "pip install" would be lovely if at all possible. :)

**Comment by nerdvegas** [comment]
I could provide a setup.py, the trouble you run into is if you expect to
continue being able to use the rez cli tools once within a rez resolved
environment though. Because the env has been changed, there's every chance
the pip-installed package will no longer function properly.

A

**Comment by gst** [comment]
I could find the root problem..

which is nothing to do with rez.

basically:  at my work we are using PYTHONPATH and in it we have pkg_resources .. prob is that it's a quite very old one.

Solution:  unset PYTHONPATH to install.

sorry for noise ;)
