### ISSUE TITLE
Windows "MAX_PATH" 260 characters limit and Rez.

### ISSUE THREAD

**Issue by KelSolaar** [nerdvegas/rez#436]
Hi,

I came across this one while building Boost with variant nesting, basically it is quite easy to hit the Windows "MAX_PATH" 260 characters limit:

``` python
D:\Documents\Development\ThirdParty\boost (master)
λ rez-release

--------------------------------------------------------------------------------
Releasing boost-1.63.0...
--------------------------------------------------------------------------------
Checking state of repository...

--------------------------------------------------------------------------------
Releasing variant 1/1...
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Program Files\Anaconda2\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Program Files\rez\Scripts\rez\rez-release.exe\__main__.py", line 2, in <module>
  File "c:\progra~1\rez\lib\site-packages\rez-2.13.0-py2.7.egg\rez\cli\_main.py", line 118, in run
    returncode = run_cmd()
  File "c:\progra~1\rez\lib\site-packages\rez-2.13.0-py2.7.egg\rez\cli\_main.py", line 110, in run_cmd
    return opts.func(opts, opts.parser, arg_groups[1:])
  File "c:\progra~1\rez\lib\site-packages\rez-2.13.0-py2.7.egg\rez\cli\release.py", line 138, in command
    variants=opts.variants)
  File "c:\progra~1\rez\lib\site-packages\rez-2.13.0-py2.7.egg\rezplugins\build_process\local.py", line 76, in release
    release_message=release_message)
  File "c:\progra~1\rez\lib\site-packages\rez-2.13.0-py2.7.egg\rez\build_process_.py", line 184, in visit_variants
    result = func(variant, **kwargs)
  File "c:\progra~1\rez\lib\site-packages\rez-2.13.0-py2.7.egg\rezplugins\build_process\local.py", line 220, in _release_variant
    install=True)
  File "c:\progra~1\rez\lib\site-packages\rez-2.13.0-py2.7.egg\rezplugins\build_process\local.py", line 116, in _build_variant_base
    shutil.rmtree(variant_build_path)
  File "C:\Program Files\Anaconda2\Lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Program Files\Anaconda2\Lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Program Files\Anaconda2\Lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Program Files\Anaconda2\Lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Program Files\Anaconda2\Lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Program Files\Anaconda2\Lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Program Files\Anaconda2\Lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Program Files\Anaconda2\Lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Program Files\Anaconda2\Lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 3] The system cannot find the path specified: 'D:\\Documents\\Development\\ThirdParty\\boost\\build\\platform-windows\\arch-AMD64\\python-2.7.13\\boost\\libs\\geometry\\doc\\doxy\\doxygen_output\\html_by_doxygen\\classboost_1_1geometry_1_1detail_1_1turns_1_1filter__continue__turns_3_01_turns_00_01true_01_4-members.html'
```

I want to document it as people might face it at some point. my workaround in that particular case was to delete the build directory manually and prepend `\\\\?\\` to any paths I use for the build/release process.

I was debating about patching Rez directly to handle that but doing the above is enough for now.

**Comment by richardssam** [comment]
I've seen that, also with building boost, fortunately my build directory
was on a remote drive, so I could remap that folder to a new drive letter.

This retarded limitation has aparently gone away in windows-10, but only if
you enable it, see:
https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

I did just come across this:
https://www.howtogeek.com/179173/ask-htg-why-is-windows-reporting-this-folder-is-too-long-to-copy/
which implies a path that looks like
\\?\c:\documents\some-really-super-long-folder-name-scheme\
where the \\? means to not impose the limit elsewhere. It didnt work for me
on windows-7 though...

Sam.


Sam.


Sam

**Comment by KelSolaar** [comment]
I have been a bit reluctant so far to enable the long path switch as I don't really know what kind of adverse side effects it can have and it is poorly documented. The `\\?\` prefix worked for my use cases so far though!

**Comment by elrond79** [comment]
Huh - I didn't know there was an option to enable long paths in Win10 -
thanks for that tidbit!
