### ISSUE TITLE
Windows: Selftest can not find cmd executable

### ISSUE THREAD

**Issue by skral** [nerdvegas/rez#480]
Hi,

2.13.1 (or any version up to the latest 2.18.0) introduces some changes that break the selftest in Windows 7.

Steps to reproduce:
1. Download 2.13.1,
2. Install: `python install.py <install_path>`
3. `set PATH=<install_path>/Scripts/rez;%PATH%`
4. `rez selftest`

4 tests will error out with the following message:
```
ERROR: test_1 (rez.tests.test_release.TestRelease)
Basic release.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\sebastian.kral\downloads\rez_install_nerdvegas_2.13.1\lib\site-packages\rez-2.13.1-py2.7.egg\rez\tests\util.py", line 159, in wrapper
    func(self, *args, **kwargs)
  File "c:\users\sebastian.kral\downloads\rez_install_nerdvegas_2.13.1\lib\site-packages\rez-2.13.1-py2.7.egg\rez\tests\util.py", line 170, in _fn
    fn(self, *args, **kwargs)
  File "c:\users\sebastian.kral\downloads\rez_install_nerdvegas_2.13.1\lib\site-packages\rez-2.13.1-py2.7.egg\rez\tests\test_release.py", line 119, in test_1
    builder.release()
  File "c:\users\sebastian.kral\downloads\rez_install_nerdvegas_2.13.1\lib\site-packages\rez-2.13.1-py2.7.egg\rezplugins\build_process\local.py", line 76, in release
    release_message=release_message)
  File "c:\users\sebastian.kral\downloads\rez_install_nerdvegas_2.13.1\lib\site-packages\rez-2.13.1-py2.7.egg\rez\build_process_.py", line 184, in visit_variants
    result = func(variant, **kwargs)
  File "c:\users\sebastian.kral\downloads\rez_install_nerdvegas_2.13.1\lib\site-packages\rez-2.13.1-py2.7.egg\rezplugins\build_process\local.py", line 220, in _release_variant
    install=True)
  File "c:\users\sebastian.kral\downloads\rez_install_nerdvegas_2.13.1\lib\site-packages\rez-2.13.1-py2.7.egg\rezplugins\build_process\local.py", line 144, in _build_variant_base
    build_type=build_type)
  File "c:\users\sebastian.kral\downloads\rez_install_nerdvegas_2.13.1\lib\site-packages\rez-2.13.1-py2.7.egg\rezplugins\build_system\bez.py", line 97, in build
    actions_callback=callback)
  File "c:\users\sebastian.kral\downloads\rez_install_nerdvegas_2.13.1\lib\site-packages\rez-2.13.1-py2.7.egg\rez\resolved_context.py", line 853, in _check
    return fn(self, *nargs, **kwargs)
  File "c:\users\sebastian.kral\downloads\rez_install_nerdvegas_2.13.1\lib\site-packages\rez-2.13.1-py2.7.egg\rez\resolved_context.py", line 1249, in execute_shell
    **Popen_args)
  File "c:\users\sebastian.kral\downloads\rez_install_nerdvegas_2.13.1\lib\site-packages\rez-2.13.1-py2.7.egg\rezplugins\shell\cmd.py", line 168, in spawn_shell
    cmd = cmd + [self.executable, "/Q", "/K", target_file]
  File "c:\users\sebastian.kral\downloads\rez_install_nerdvegas_2.13.1\lib\site-packages\rez-2.13.1-py2.7.egg\rezplugins\shell\cmd.py", line 25, in executable
    cls._executable = Shell.find_executable('cmd')
  File "c:\users\sebastian.kral\downloads\rez_install_nerdvegas_2.13.1\lib\site-packages\rez-2.13.1-py2.7.egg\rez\shells.py", line 112, in find_executable
    raise RuntimeError("Couldn't find executable '%s'." % name)
RuntimeError: Couldn't find executable 'cmd'.
```

The tests failing:
```
test_1 (rez.tests.test_release.TestRelease) - Basic release.
test_2_variant_add (rez.tests.test_release.TestRelease) - Test variant installation on release
test_rex_code (rez.tests.test_shells.TestShells) - Test that Rex code run in the shell creates the environment variable
test_rez_command (rez.tests.test_shells.TestShells)
```

I am attaching two logs, the entire one and just the errors.
[entire.log](https://github.com/nerdvegas/rez/files/1721775/entire.log)
[errors.log](https://github.com/nerdvegas/rez/files/1721776/errors.log)

2.13.0 works which is why I took a look at these changes but I do not know enough about the changes to fix it properly. Here is the link to the comparison of the two tags:
https://github.com/nerdvegas/rez/compare/2.13.0...2.13.1

Since this is something that only affects the current Python environment I would think our normal usage via command line calls should be fine but it's far from ideal that the Windows tests are broken and I would like to help fix those.

Let me know if there is any other information I can provide.

Thank you for your help.

Cheers,
Sebastian

**Comment by skral** [comment]
Just a quick update, it is the following line:

https://github.com/nerdvegas/rez/compare/2.13.0...2.13.1#diff-ced118143cfe33b8508afbfae79bb420R1048

Not sure how to fix it yet but at least nobody else needs to go hunting for it.

Cheers,
Sebastian
