### ISSUE TITLE
memcache issues when using the preprocess function

### ISSUE THREAD

**Issue by JeanChristopheMorinRodeoFX** [nerdvegas/rez#514]
We started to use memcache with Rez a couple of months ago and since then we have some weird issues when we use the `preprocess` function in our packages. The issue is with rez-build and only happens with rez-build.

The error I have is:
```python
Traceback (most recent call last):
  File "/mnt/users/jcmorin/rez_install_osx/bin/rez/rez-build", line 4, in <module>
    run('build')
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/cli/_main.py", line 102, in run
    opts = parser.parse_args(arg_groups[0])
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/vendor/argparse.py", line 1703, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/vendor/argparse.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/vendor/argparse.py", line 1923, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/vendor/argparse.py", line 1900, in consume_positionals
    take_action(action, args)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/vendor/argparse.py", line 1809, in take_action
    action(self, namespace, argument_values, option_string)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/cli/_util.py", line 56, in __call__
    self._setup_subparser(parser_name, parser)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/cli/_util.py", line 62, in _setup_subparser
    help_ = parser.setup_subparser(parser_name, parser)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/cli/_main.py", line 34, in __call__
    mod.setup_parser(parser)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/cli/build.py", line 67, in setup_parser
    setup_parser_common(parser)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/cli/build.py", line 18, in setup_parser_common
    clss = get_valid_build_systems(os.getcwd())
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/build_system.py", line 22, in get_valid_build_systems
    if cls.is_valid_root(working_dir):
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rezplugins/build_system/custom.py", line 36, in is_valid_root
    package = get_developer_package(path)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/packages_.py", line 552, in get_developer_package
    return DeveloperPackage.from_path(path)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/developer_package.py", line 54, in from_path
    data = load_from_file(filepath, format_)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/serialise.py", line 92, in load_from_file
    update_data_callback=update_data_callback)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/utils/memcached.py", line 352, in wrapper
    min_compress_len=min_compress_len)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/utils/memcached.py", line 85, in set
    min_compress_len=min_compress_len)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/vendor/memcache/memcache.py", line 585, in set
    return self._set("set", key, val, time, min_compress_len)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/vendor/memcache/memcache.py", line 836, in _set
    return _unsafe_set()
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/vendor/memcache/memcache.py", line 813, in _unsafe_set
    store_info = self._val_to_store_info(val, min_compress_len)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.14.1-py2.7.egg/rez/vendor/memcache/memcache.py", line 783, in _val_to_store_info
    pickler.dump(val)
TypeError: expected string or Unicode object, NoneType found
```

It is super annoying as you can guess. I tried to dig and find what's wrong but I was limmited in time back then, and still a little. To workaround, I need to manually disable memcache from my local rez settings.

The issue happens with something as simple as is present in my `package.py` file:
```python
def preprocess(this, data):
    pass
```

Is this something known?

Thanks a lot!

**Comment by JeanChristopheMorinRodeoFX** [comment]
Here is the error with the latest version of rez (the one in the issue description comes from rez 2.14):

This one comes from 2.18.0
```python
Traceback (most recent call last):
  File "/mnt/users/jcmorin/rez_install_osx/bin/rez/rez-build", line 4, in <module>
    run('build')
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/cli/_main.py", line 102, in run
    opts = parser.parse_args(arg_groups[0])
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/vendor/argparse.py", line 1703, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/vendor/argparse.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/vendor/argparse.py", line 1923, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/vendor/argparse.py", line 1900, in consume_positionals
    take_action(action, args)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/vendor/argparse.py", line 1809, in take_action
    action(self, namespace, argument_values, option_string)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/cli/_util.py", line 56, in __call__
    self._setup_subparser(parser_name, parser)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/cli/_util.py", line 62, in _setup_subparser
    help_ = parser.setup_subparser(parser_name, parser)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/cli/_main.py", line 34, in __call__
    mod.setup_parser(parser)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/cli/build.py", line 67, in setup_parser
    setup_parser_common(parser)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/cli/build.py", line 18, in setup_parser_common
    clss = get_valid_build_systems(os.getcwd())
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/build_system.py", line 22, in get_valid_build_systems
    if cls.is_valid_root(working_dir):
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rezplugins/build_system/custom.py", line 36, in is_valid_root
    package = get_developer_package(path)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/packages_.py", line 552, in get_developer_package
    return DeveloperPackage.from_path(path, format=format)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/developer_package.py", line 80, in from_path
    data = load_from_file(filepath, format_)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/serialise.py", line 93, in load_from_file
    update_data_callback=update_data_callback)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/utils/memcached.py", line 352, in wrapper
    min_compress_len=min_compress_len)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/utils/memcached.py", line 85, in set
    min_compress_len=min_compress_len)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/vendor/memcache/memcache.py", line 585, in set
    return self._set("set", key, val, time, min_compress_len)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/vendor/memcache/memcache.py", line 836, in _set
    return _unsafe_set()
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/vendor/memcache/memcache.py", line 813, in _unsafe_set
    store_info = self._val_to_store_info(val, min_compress_len)
  File "/mnt/users/jcmorin/rez_install_osx/lib/python2.7/site-packages/rez-2.18.0-py2.7.egg/rez/vendor/memcache/memcache.py", line 783, in _val_to_store_info
    pickler.dump(val)
TypeError: expected string or Unicode object, NoneType found
```

**Comment by nerdvegas** [comment]
Hi Jean,

I have not heard of this error before no. I'm surprised memcache is getting
hit when loading a developer package... and it seems like this should be
happening to a lot of people if that were the case. Unless preprocessing
just isn't getting used much yet?

My guess at what's going on - while memcached is disabled for local
packages (iirc), perhaps it (incorrectly) was in use for developer packages
(ie unbuilt packages) this while time, and nobody noticed. The introduction
of package-attributes-as-functions would then break the serialization into
memcache. But preprocess is just one example of an attribute-as-function so
again I'm surprised this hasn't come up before. Perhaps it's an edge case.

Anyway my studio is going to be using package preprocessing soon so it
sounds like I'm gonna have to fix this soon!

Thx
A
