### ISSUE TITLE
rez-bind --quickstart error

### ISSUE THREAD

**Issue by 0d3nMjolnir** [nerdvegas/rez#544]
I've just installed a fresh build of Mint 19 os and trying to get past the Installation stage in your docs. 

`rez-bind --quickstart`

I'm getting the following error. I've trawled throught other issues but couldn't get an answer.

`mjolnir@vahalla:/usr/sw/rez/lib/python2.7/site-packages$ rez-bind --quickstart
Binding platform into /home/mjolnir/packages...
Traceback (most recent call last):
  File "/usr/sw/rez/bin/rez/rez-bind", line 4, in <module>
    run('bind')
  File "/usr/sw/rez/local/lib/python2.7/site-packages/rez-2.23.1-py2.7.egg/rez/cli/_main.py", line 144, in run
    returncode = run_cmd()
  File "/usr/sw/rez/local/lib/python2.7/site-packages/rez-2.23.1-py2.7.egg/rez/cli/_main.py", line 136, in run_cmd
    return opts.func(opts, opts.parser, extra_arg_groups)
  File "/usr/sw/rez/local/lib/python2.7/site-packages/rez-2.23.1-py2.7.egg/rez/cli/bind.py", line 75, in command
    quiet=True)
  File "/usr/sw/rez/local/lib/python2.7/site-packages/rez-2.23.1-py2.7.egg/rez/package_bind.py", line 112, in bind_package
    quiet=quiet)
  File "/usr/sw/rez/local/lib/python2.7/site-packages/rez-2.23.1-py2.7.egg/rez/package_bind.py", line 176, in _bind_package
    parser=bind_parser)
  File "/usr/sw/rez/local/lib/python2.7/site-packages/rez-2.23.1-py2.7.egg/rez/bind/platform.py", line 16, in bind
    pkg.version = version
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/sw/rez/local/lib/python2.7/site-packages/rez-2.23.1-py2.7.egg/rez/package_maker__.py", line 185, in make_package
    variant_ = variant.install(path, dry_run=True)
  File "/usr/sw/rez/local/lib/python2.7/site-packages/rez-2.23.1-py2.7.egg/rez/packages_.py", line 370, in install
    overrides=overrides)
  File "/usr/sw/rez/lib/python2.7/site-packages/rez-2.23.1-py2.7.egg/rezplugins/package_repository/filesystem.py", line 561, in install_variant
    lock.acquire(timeout=_settings.file_lock_timeout)
  File "/usr/sw/rez/local/lib/python2.7/site-packages/rez-2.23.1-py2.7.egg/rez/vendor/lockfile/linklockfile.py", line 20, in acquire
    raise LockFailed("failed to create %s" % self.unique_name)
rez.vendor.lockfile.LockFailed: failed to create /home/mjolnir/packages/vahalla-3dfb8740.11840-4155522034056001893
`

**Comment by nerdvegas** [comment]
It may simple be that /home/mjolnir/packages does not exist - if so, create
it and try again.

The error message is misleading in this case - this has been fixed in the
PR that I'm currently working on.

Thx
A

**Comment by 0d3nMjolnir** [comment]
So turns out that directory exists. Re-ran the code as root and created the directory /root/packages which started binding packages. However I got an error on my Python2.7 libraries. 

removed 2.7 and re-installed Python 2.7 which bound more packages but then got a different error.

`root@vahalla:/home/mjolnir/packages# rez-bind --quickstart
Binding platform into /root/packages...
21:10:34 WARNING  Skipping installation: Package variant already exists: /root/packages/platform/linux/package.py[]
Binding arch into /root/packages...
21:10:34 WARNING  Skipping installation: Package variant already exists: /root/packages/arch/x86_64/package.py[]
Binding os into /root/packages...
21:10:34 WARNING  Skipping installation: Package variant already exists: /root/packages/os/LinuxMint-19/package.py[]
Binding python into /root/packages...
21:10:34 WARNING  Skipping installation: Package variant already exists: /root/packages/python/2.7.15/package.py[0]
Binding rez into /root/packages...
21:10:34 WARNING  Skipping installation: Package variant already exists: /root/packages/rez/2.23.1/package.py[0]
Binding rezgui into /root/packages...
21:10:34 WARNING  Skipping installation: Package variant already exists: /root/packages/rezgui/2.23.1/package.py[0]
Binding setuptools into /root/packages...
21:10:34 ERROR    RezBindError: Couldn't determine version of module setuptools: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named setuptools
`

**Comment by 0d3nMjolnir** [comment]
Success loaded the extra libraries and ran as root.
