### ISSUE TITLE
"WindowsError" exception raised when building package if the user target "Packages" directory has existing files.

### ISSUE THREAD

**Issue by KelSolaar** [nerdvegas/rez#591]
Hi,

While upgrading from 2.16.0 to 2.28.0, I get a `WindowsError` exception raised when building a package if the target directory, i.e. my user *Packages* directory, has existing files:

```python
Traceback (most recent call last):
  File "c:\progra~1\rez\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\progra~1\rez\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Program Files\rez\Scripts\rez\rez-build.exe\__main__.py", line 2, in <module>
  File "c:\progra~1\rez\lib\site-packages\rez-2.28.0-py2.7.egg\rez\cli\_main.py", line 144, in run
    returncode = run_cmd()
  File "c:\progra~1\rez\lib\site-packages\rez-2.28.0-py2.7.egg\rez\cli\_main.py", line 136, in run_cmd
    return opts.func(opts, opts.parser, extra_arg_groups)
  File "c:\progra~1\rez\lib\site-packages\rez-2.28.0-py2.7.egg\rez\cli\build.py", line 155, in command
    variants=opts.variants)
  File "c:\progra~1\rez\lib\site-packages\rez-2.28.0-py2.7.egg\rezplugins\build_process\local.py", line 37, in build
    install=install)
  File "c:\progra~1\rez\lib\site-packages\rez-2.28.0-py2.7.egg\rez\build_process_.py", line 197, in visit_variants
    result = func(variant, **kwargs)
  File "c:\progra~1\rez\lib\site-packages\rez-2.28.0-py2.7.egg\rezplugins\build_process\local.py", line 231, in _build_variant
    variant.install(install_path)
  File "c:\progra~1\rez\lib\site-packages\rez-2.28.0-py2.7.egg\rez\packages_.py", line 401, in install
    overrides=overrides)
  File "c:\progra~1\rez\lib\site-packages\rez-2.28.0-py2.7.egg\rezplugins\package_repository\filesystem.py", line 602, in install_variant
    variant = _create_variant()
  File "c:\progra~1\rez\lib\site-packages\rez-2.28.0-py2.7.egg\rezplugins\package_repository\filesystem.py", line 595, in _create_variant
    overrides=overrides
  File "c:\progra~1\rez\lib\site-packages\rez-2.28.0-py2.7.egg\rezplugins\package_repository\filesystem.py", line 1050, in _create_variant
    dump_package_data(package_data, buf=f, format_=package_format)
  File "c:\progra~1\rez\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "c:\progra~1\rez\lib\site-packages\rez-2.28.0-py2.7.egg\rez\serialise.py", line 68, in open_file_for_write
    f.write(content)
  File "c:\progra~1\rez\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "c:\progra~1\rez\lib\site-packages\rez-2.28.0-py2.7.egg\rez\vendor\atomicwrites\__init__.py", line 154, in _open
    self.commit(f)
  File "c:\progra~1\rez\lib\site-packages\rez-2.28.0-py2.7.egg\rez\vendor\atomicwrites\__init__.py", line 185, in commit
    replace_atomic(f.name, self._path)
  File "c:\progra~1\rez\lib\site-packages\rez-2.28.0-py2.7.egg\rez\vendor\atomicwrites\__init__.py", line 92, in replace_atomic
    return _replace_atomic(src, dst)
  File "c:\progra~1\rez\lib\site-packages\rez-2.28.0-py2.7.egg\rez\vendor\atomicwrites\__init__.py", line 75, in _replace_atomic
    _windows_default_flags | _MOVEFILE_REPLACE_EXISTING
  File "c:\progra~1\rez\lib\site-packages\rez-2.28.0-py2.7.egg\rez\vendor\atomicwrites\__init__.py", line 70, in _handle_errors
    raise WinError()
WindowsError: [Error 5] Access is denied.
```

If I remove the target directory it is all good.

**Comment by KelSolaar** [comment]
Hang on, it might be an issue on my system actually!

**Comment by KelSolaar** [comment]
Confirming that the `package.py` file is set read-only by the `rez-build -i` process thus next invocation it breaks.

**Comment by mottosso** [comment]
Related to https://github.com/nerdvegas/rez/pull/598

**Comment by nerdvegas** [comment]
Closed by https://github.com/nerdvegas/rez/pull/598
