### ISSUE TITLE
rezbuild.py broken

### ISSUE THREAD

**Issue by mottosso** [nerdvegas/rez#619]
Recent commit [here](https://github.com/nerdvegas/rez/commit/7a5688944bd2d90ba539ac61669a926a2184ba1a#r33320111) broken the use of `rezbuild.py`.

```bash
$ rez build
...
    mod.setup_parser(parser)
  File "c:\users\manima\dropbox\dev\anima\rez2\lib\site-packages\rez-2.29.0-py2.7.egg\rez\cli\build.py", line 97, in setup_parser
    setup_parser_common(parser)
  File "c:\users\manima\dropbox\dev\anima\rez2\lib\site-packages\rez-2.29.0-py2.7.egg\rez\cli\build.py", line 49, in setup_parser_common
    cls_.bind_cli(parser, group)
```

With the following files.

```bash
my_package/
  package.py
  rezbuild.py
```

**Comment by instinct-vfx** [comment]
What are you testing this with? Using 2.29.0 i can not reproduce this. At least not with my own packages. Both packages with custom arguments and without build just fine. @lambdaclan

**Comment by mottosso** [comment]
It's recent, from 2.29.1 onwards.

**Comment by instinct-vfx** [comment]
Sorry, i meant 2.29.1. Seems to work fine for me:
![image](https://user-images.githubusercontent.com/243828/56888435-40f41780-6a74-11e9-9889-79189f945072.png)

**Comment by instinct-vfx** [comment]
Okay, so this does break, but it only breaks with legacy rezbuild.py setups. I have migrated my packages to using custom build commands instead and that still works.

**Comment by RudeyPunk** [comment]
I am having an issue that may be related.

I am a Rez  noob, trying to understand how Rez works with Windows; (windows-10.0.17134, Rez v2.29.1). I am trying to do a "rez-build" on the supplied "example-package" and I'm having python problems with the default content:

>>>> C:\rez-master\rez-master\example_packages\hello_world>rez-build --install
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27amd64\Lib\site-packages\Rez\Scripts\rez\rez-build.exe\__main__.py", line 2, in <module>
  File "c:\python27amd64\lib\site-packages\rez\lib\site-packages\rez-2.29.1-py2.7.egg\rez\cli\_main.py", line 119, in run
    opts = parser.parse_args(arg_groups[0])
  File "c:\python27amd64\lib\site-packages\rez\lib\site-packages\rez-2.29.1-py2.7.egg\rez\vendor\argparse.py", line 1703, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "c:\python27amd64\lib\site-packages\rez\lib\site-packages\rez-2.29.1-py2.7.egg\rez\vendor\argparse.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "c:\python27amd64\lib\site-packages\rez\lib\site-packages\rez-2.29.1-py2.7.egg\rez\vendor\argparse.py", line 1923, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "c:\python27amd64\lib\site-packages\rez\lib\site-packages\rez-2.29.1-py2.7.egg\rez\vendor\argparse.py", line 1900, in consume_positionals
    take_action(action, args)
  File "c:\python27amd64\lib\site-packages\rez\lib\site-packages\rez-2.29.1-py2.7.egg\rez\vendor\argparse.py", line 1809, in take_action
    action(self, namespace, argument_values, option_string)
  File "c:\python27amd64\lib\site-packages\rez\lib\site-packages\rez-2.29.1-py2.7.egg\rez\cli\_util.py", line 74, in __call__
    self._setup_subparser(parser_name, parser)
  File "c:\python27amd64\lib\site-packages\rez\lib\site-packages\rez-2.29.1-py2.7.egg\rez\cli\_util.py", line 80, in _setup_subparser
    help_ = parser.setup_subparser(parser_name, parser)
  File "c:\python27amd64\lib\site-packages\rez\lib\site-packages\rez-2.29.1-py2.7.egg\rez\cli\_main.py", line 33, in __call__
    mod.setup_parser(parser)
  File "c:\python27amd64\lib\site-packages\rez\lib\site-packages\rez-2.29.1-py2.7.egg\rez\cli\build.py", line 97, in setup_parser
    setup_parser_common(parser)
  File "c:\python27amd64\lib\site-packages\rez\lib\site-packages\rez-2.29.1-py2.7.egg\rez\cli\build.py", line 49, in setup_parser_common
    cls_.bind_cli(parser, group)
TypeError: bind_cli() takes exactly 2 arguments (3 given)

I get this exact same behavior if I use "rezbuild.py", "CMakeLists.txt" or just "rez-build -i"
Any kind of help would be be extremely appreciated!

**Comment by nerdvegas** [comment]
Note that I've fixed this in 2.30.0 just now, apologies for the breakage on master.
@RudeyPunk

**Comment by nerdvegas** [comment]
closed by https://github.com/nerdvegas/rez/releases/tag/2.30.0

**Comment by RudeyPunk** [comment]
It's all good,! Thanks Allan!
