### ISSUE TITLE
[Bug] Unable to catch RexUndefinedVariableError

### ISSUE THREAD

**Issue by mottosso** [nerdvegas/rez#635]
When a package is referencing a non-existent variable, the associated exception is discarded, and replaced with a generic `SourceCodeExecError`, which means it can't be handled, without parsing the resulting text for clues. This applies to *any* exception happening in a `package.py`.

**package.py**

```python
name = "my_package"

def commands():
  env.PYTHONPATH.append("{env.MISSING_VARIABLE}")
```

**Problem**

```python
from rez.resolved_context import ResolvedContext
ctx = ResolvedContext (["my_package"])
ctx.get_environ()
# Traceback (most recent call last):
# ...
# RexUndefinedVariableError: Referenced undefined environment variable: MISSING_VARIABLE
```

<details>
<summary>Full Traceback</summary>

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\virtualenv\rez\lib\site-packages\rez\resolved_context.py", line 873, in _check
    return fn(self, *nargs, **kwargs)
  File "c:\virtualenv\rez\lib\site-packages\rez\resolved_context.py", line 934, in get_environ
    self._execute(executor)
  File "c:\virtualenv\rez\lib\site-packages\rez\utils\memcached.py", line 253, in wrapper
    return func(*nargs, **kwargs)
  File "c:\virtualenv\rez\lib\site-packages\rez\resolved_context.py", line 1678, in _execute
    executor.execute_code(commands, isolate=True)
  File "c:\virtualenv\rez\lib\site-packages\rez\rex.py", line 1211, in execute_code
    _apply()
  File "c:\virtualenv\rez\lib\site-packages\rez\rex.py", line 1198, in _apply
    exec_namespace=self.globals)
  File "c:\virtualenv\rez\lib\site-packages\rez\rex.py", line 1179, in compile_code
    reraise(e, RexError)
  File "c:\virtualenv\rez\lib\site-packages\rez\utils\__init__.py", line 20, in reraise
    six.reraise(new_exc_cls, exc, traceback)
  File "c:\virtualenv\rez\lib\site-packages\rez\rex.py", line 1173, in compile_code
    code.exec_(globals_=exec_namespace)
  File "c:\virtualenv\rez\lib\site-packages\rez\utils\sourcecode.py", line 220, in exec_
    short_msg=str(e))
rez.exceptions.RexError: Failed to execute <c:\packages\my_package\2.3.11\package.py:commands>:
Traceback (most recent call last):
  File "c:\virtualenv\rez\lib\site-packages\rez\utils\sourcecode.py", line 215, in exec_
    exec(pyc, globals_)
  File "<c:\packages\my_package\2.3.11\package.py:commands>", line 11, in <module>
  File "c:\virtualenv\rez\lib\site-packages\rez\rex.py", line 262, in expandvars
    value = str(self._format(value))
  File "c:\virtualenv\rez\lib\site-packages\rez\rex.py", line 225, in _format
    return EscapedString.promote(value).formatted(self.formatter)
  File "c:\virtualenv\rez\lib\site-packages\rez\rex.py", line 778, in formatted
    value = func(value)
  File "c:\virtualenv\rez\lib\site-packages\rez\rex.py", line 1251, in expand
    return self.formatter.format(str(value))
  File "c:\virtualenv\rez\lib\site-packages\rez\rex.py", line 902, in format
    return Formatter.format(self, format_string_, *args, **kwargs)
  File "c:\Python27\Lib\string.py", line 559, in format
    return self.vformat(format_string, args, kwargs)
  File "c:\Python27\Lib\string.py", line 563, in vformat
    result = self._vformat(format_string, args, kwargs, used_args, 2)
  File "c:\Python27\Lib\string.py", line 596, in _vformat
    result.append(self.format_field(obj, format_spec))
  File "c:\virtualenv\rez\lib\site-packages\rez\rex.py", line 912, in format_field
    return format(value, format_spec)
  File "c:\virtualenv\rez\lib\site-packages\rez\rex.py", line 1015, in __str__
    return self.value()
  File "c:\virtualenv\rez\lib\site-packages\rez\rex.py", line 1007, in value
    return self.get()
  File "c:\virtualenv\rez\lib\site-packages\rez\rex.py", line 1004, in get
    return self._environ_map.manager.getenv(self.name)
  File "c:\virtualenv\rez\lib\site-packages\rez\rex.py", line 272, in getenv
    "Referenced undefined environment variable: %s" % expanded_key)
RexUndefinedVariableError: Referenced undefined environment variable: MISSING_VARIABLE
```

</details>

Even though the exception type is `rez.exceptions.RexError`. Note the dual tracebacks, one printed by another.

What I'd like to be able to do is:

```python
try:
  ctx.get_environ()
except rez.exceptions.RexUndefinedVariableError:
  # Handle it
```

**Source**

The problem is coming from here:

https://github.com/nerdvegas/rez/blob/3c194ba105330b509f9434881abe38b0c23636ad/src/rez/utils/sourcecode.py#L214-L220

### Proposal

There's config option called [catch_rex_errors](https://github.com/nerdvegas/rez/wiki/Configuring-Rez#catch_rex_errors) that I was expecting to work for this usecase, but it appears to only relate to certain rex-related errors.

Would it make sense to implement this here as well?

**Comment by nerdvegas** [comment]
So, yes you should be able to catch the RexUndefinedVariableError, but I don't think it's as simple as:

```
try:
  ctx.get_environ()
except rez.exceptions.RexUndefinedVariableError:
  # Handle it
```

The problem with this is that you lose information, that you can't get from the callstack or anywhere else. What I mean is, in `ctx` above, a rex error has occurred - but in what package, and in what function within that package definition? (a package can have multiple). Note that that info is present in the RexError (although not properly accessible):

```
rez.exceptions.RexError: Failed to execute <c:\packages\my_package\2.3.11\package.py:commands>:
```

Specifically I think the bug(s) that you've found are:
* A PackageCommandError should be raised, not a RexError;
* PackageCommandError should provide the variant, name of the offending function ('commands' in this case), and the original exception object;
* Also yes I think catch_rex_errors should be honoured here.

So you should be able to do this:

```
try:
  ctx.get_environ()
except PackageCommandError as e:
  print >> stderr, "Error in pkg %s, func %s: %s" % (e.variant, e.funcname, e.rex_exc)
  raise e.rex_exc  # raise original rex error
```
