### ISSUE TITLE
[BUG] Error running tests

### ISSUE THREAD

**Issue by bpabel** [nerdvegas/rez#640]
I get several of the following errors when running the tests on windows.  The error is the same whether the tests are run from an admin shell or not.

Has anyone had a similar issue running the tests?

```
======================================================================
ERROR: tearDownClass (rez.tests.test_shells.TestShells)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\007br\rez\rez\src\rez\tests\test_shells.py", line 46, in tearDownClass
    TempdirMixin.tearDownClass()
  File "C:\Users\007br\rez\rez\src\rez\tests\util.py", line 105, in tearDownClass
    shutil.rmtree(cls.root)
  File "C:\Python27\lib\shutil.py", line 261, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 261, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 261, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 266, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Python27\lib\shutil.py", line 264, in rmtree
    os.remove(fullname)
WindowsError: [Error 5] Access is denied: 'c:\\users\\007br\\appdata\\local\\temp\\rez_selftest_rhj5ww\\packages\\hello_world\\1.0\\package.py'
```

**Comment by mottosso** [comment]
Yes, you'll need this.

- https://github.com/nerdvegas/rez/pull/598
