### ISSUE TITLE
rez-depends -- 'ProgressBar' object is not an iterator (py-3, rez-2.47.4)

### ISSUE THREAD

**Issue by willjp** [nerdvegas/rez#765]
``` yaml
platform: windows
rez: 2.47.4
rez-python: 3.6.5
```
Hey guys, just updated. I noticed an issue with rez-depends under py3/windows on the latest release.

rez-depends fails with a stacktrace:
``` python
C:\Users\willjp\Desktop\tmp\tma\src\core\tmatoolRezPackageBuilder>rez-depends tmacoreAppLauncher
Traceback (most recent call last):
  File "C:\Python-3.6.5\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python-3.6.5\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\willjp\Documents\tma\rez\install\Scripts\rez\rez-depends.exe\__main__.py", line 7, in <module>
  File "c:\users\willjp\documents\tma\rez\install\lib\site-packages\rez\cli\_entry_points.py", line 138, in run_rez_depends
    return run("depends")
  File "c:\users\willjp\documents\tma\rez\install\lib\site-packages\rez\cli\_main.py", line 152, in run
    returncode = run_cmd()
  File "c:\users\willjp\documents\tma\rez\install\lib\site-packages\rez\cli\_main.py", line 144, in run_cmd
    return opts.func(opts, opts.parser, extra_arg_groups)
  File "c:\users\willjp\documents\tma\rez\install\lib\site-packages\rez\cli\depends.py", line 63, in command
    private_build_requires=opts.private_build_requires)
  File "c:\users\willjp\documents\tma\rez\install\lib\site-packages\rez\package_search.py", line 88, in get_reverse_dependency_tree
    next(bar)
TypeError: 'ProgressBar' object is not an iterator
```

When I have some extra time I'll see about making a pull request if it's helpful :).

**Comment by maxnbk** [comment]
Got you covered in #766 PR. This is my mistake, in batching updates to py3 centric iterators, whereas this progress library really just expects the oldschool iterator handling in spite of advertising itself as py3 friendly.

**Comment by willjp** [comment]
oh right on! thanks for letting me know!
