### ISSUE TITLE
NameError: name 'popen' is not defined (typo in rezplugins.shell.cmd) (rez-2.47.7)

### ISSUE THREAD

**Issue by willjp** [nerdvegas/rez#771]
Hey guys, this one's just a typo.

```
C:\Users\willjp>rez-env rez
Traceback (most recent call last):
  File "C:\Python-3.6.5\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python-3.6.5\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\willjp\Documents\rez\install\Scripts\rez\rez-env.exe\__main__.py", line 7, in <module>
  File "c:\users\willjp\documents\rez\install\lib\site-packages\rez\cli\_entry_points.py", line 152, in run_rez_env
    return run("env")
  File "c:\users\willjp\documents\rez\install\lib\site-packages\rez\cli\_main.py", line 152, in run
    returncode = run_cmd()
  File "c:\users\willjp\documents\rez\install\lib\site-packages\rez\cli\_main.py", line 144, in run_cmd
    return opts.func(opts, opts.parser, extra_arg_groups)
  File "c:\users\willjp\documents\rez\install\lib\site-packages\rez\cli\env.py", line 250, in command
    block=True)
  File "c:\users\willjp\documents\rez\install\lib\site-packages\rez\resolved_context.py", line 877, in _check
    return fn(self, *nargs, **kwargs)
  File "c:\users\willjp\documents\rez\install\lib\site-packages\rez\resolved_context.py", line 1251, in execute_shell
    self._execute(executor)
  File "c:\users\willjp\documents\rez\install\lib\site-packages\rez\utils\memcached.py", line 254, in wrapper
    return func(*nargs, **kwargs)
  File "c:\users\willjp\documents\rez\install\lib\site-packages\rez\resolved_context.py", line 1697, in _execute
    executor.append_system_paths()
  File "c:\users\willjp\documents\rez\install\lib\site-packages\rez\rex.py", line 1152, in append_system_paths
    paths = sh.get_syspaths()
  File "c:\users\willjp\documents\rez\install\lib\site-packages\rezplugins\shell\cmd.py", line 125, in get_syspaths
    p = popen(cmd, stdout=subprocess.PIPE,
NameError: name 'popen' is not defined
```

**Comment by JeanChristopheMorinPerso** [comment]
This should get fixed by #770  I think. @bfloch can you confirm?

**Comment by willjp** [comment]
I checked the PR you mentioned, it is the same line number. That would fix it.

**Comment by bfloch** [comment]
Same bug.
