### ISSUE TITLE
"AttributeError" exception raised when using "rez-gui" Package Browser with Pyside2 .

### ISSUE THREAD

**Issue by KelSolaar** [nerdvegas/rez#849]
Title says it all! :)

```
C:\Users\thomas>rez-gui
Traceback (most recent call last):
  File "c:\progra~1\rez\lib\site-packages\rezgui\windows\MainWindow.py", line 72, in _open_package_browser
    subwindow = BrowsePackageSubWindow()
  File "c:\progra~1\rez\lib\site-packages\rezgui\windows\BrowsePackageSubWindow.py", line 15, in __init__
    widget = BrowsePackagePane()
  File "c:\progra~1\rez\lib\site-packages\rezgui\widgets\BrowsePackagePane.py", line 20, in __init__
    self.browse = BrowsePackageWidget(self.context_model)
  File "c:\progra~1\rez\lib\site-packages\rezgui\widgets\BrowsePackageWidget.py", line 26, in __init__
    callback=package_selectable_callback)
  File "c:\progra~1\rez\lib\site-packages\rezgui\widgets\PackageVersionsTable.py", line 32, in __init__
    vh.setResizeMode(QtWidgets.QHeaderView.ResizeToContents)
AttributeError: 'PySide2.QtWidgets.QHeaderView' object has no attribute 'setResizeMode'
```

Cheers,

Thomas

**Comment by nerdvegas** [comment]
Closed by https://github.com/nerdvegas/rez/pull/851
