### ISSUE TITLE
Cannot call get_developer_package on a previously modified package

### ISSUE THREAD

**Issue by ColinKennedy** [nerdvegas/rez#857]
If you call `get_developer_package`, modify the package.py, and then call it again on the same directory, you get a serialization error.

Pre-production Steps:

```python
import os
import textwrap
from rez import packages_


path = "/tmp/testout"
package_path = os.path.join(path, "package.py")

with open(package_path, "w") as handler:
    handler.write(
        textwrap.dedent(
            """\
            # -*- coding: utf-8 -*-

            name = "foo_bar"

            version = "1.0.0"

            build_command = "echo 'asdf'"

            def commands():
                pass
            """
        )
    )

package = packages_.get_developer_package(path)

with open(package.filepath, "w") as handler:
    handler.write(
        textwrap.dedent(
            """\
            # -*- coding: utf-8 -*-

            name = "foo_bar"

            version = "1.1.0"

            requires = [
                "python-2",
            ]

            build_command = "echo 'asdf'"

            def commands():
                pass
            """
        )
    )

package = packages_.get_developer_package(path)
```

Running the code above on Linux creates this traceback

```
Traceback (most recent call last):
  File "/home/selecaotwo///temp/test.py", line 303, in <module>
    package = packages_.get_developer_package(path)
  File "/home/selecaotwo/packages/rez/2.53.0/platform-linux/arch-x86_64/os-CentOS-7.6.1810/rez/packages.py", line 601, in get_developer_package
    return DeveloperPackage.from_path(path, format=format)
  File "/home/selecaotwo/packages/rez/2.53.0/platform-linux/arch-x86_64/os-CentOS-7.6.1810/rez/developer_package.py", line 92, in from_path
    data = load_from_file(filepath, format_, disable_memcache=True)
  File "/home/selecaotwo/packages/rez/2.53.0/platform-linux/arch-x86_64/os-CentOS-7.6.1810/rez/serialise.py", line 124, in load_from_file
    update_data_callback=update_data_callback)
  File "/home/selecaotwo/packages/rez/2.53.0/platform-linux/arch-x86_64/os-CentOS-7.6.1810/rez/serialise.py", line 161, in _load_file
    result = load_func(f, filepath=filepath)
  File "/home/selecaotwo/packages/rez/2.53.0/platform-linux/arch-x86_64/os-CentOS-7.6.1810/rez/serialise.py", line 218, in load_py
    return _load_py(stream, filepath=filepath)
  File "/home/selecaotwo/packages/rez/2.53.0/platform-linux/arch-x86_64/os-CentOS-7.6.1810/rez/serialise.py", line 256, in _load_py
    result = process_python_objects(result, filepath=filepath)
  File "/home/selecaotwo/packages/rez/2.53.0/platform-linux/arch-x86_64/os-CentOS-7.6.1810/rez/serialise.py", line 380, in process_python_objects
    data = _process(data)
  File "/home/selecaotwo/packages/rez/2.53.0/platform-linux/arch-x86_64/os-CentOS-7.6.1810/rez/serialise.py", line 298, in _process
    value[k] = _process(v)
  File "/home/selecaotwo/packages/rez/2.53.0/platform-linux/arch-x86_64/os-CentOS-7.6.1810/rez/serialise.py", line 353, in _process
    eval_as_function=False)
  File "/home/selecaotwo/packages/rez/2.53.0/platform-linux/arch-x86_64/os-CentOS-7.6.1810/rez/utils/sourcecode.py", line 104, in __init__
    self._init_from_func()
  File "/home/selecaotwo/packages/rez/2.53.0/platform-linux/arch-x86_64/os-CentOS-7.6.1810/rez/utils/sourcecode.py", line 124, in _init_from_func
    loc = getsourcelines(self.func)[0][len(self.decorators) + 1:]
  File "/usr/lib64/python2.7/inspect.py", line 690, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/lib64/python2.7/inspect.py", line 580, in findsource
    if pat.match(lines[lnum]): break
IndexError: list index out of range
```

Given that `get_developer_package` loads packages directly and not from memcache, I would've expected this to work, no matter how many times I modified the original package.py.

If there's a simple way to get around this issue (e.g. flushing data or some other method) please let me know. Thank you!

**Comment by nerdvegas** [comment]
Yeah I'd expect this to work also. At the very least I'd have thought you'd get back the same unchanged package (there is a global cache in rez, unrelated to memcached. It's unfortunate that it's global, that's historical). Will have to take a look.

In the meantime, you can clear this cache with `rez.system.system.clear_caches()`. Please let me know if this works.

Thx
A

**Comment by ColinKennedy** [comment]
I tried adding `rez.system.system.clear_caches()` to several spots in the code by unfortunately it still fails with the same error. For curiosity's sake, I also tried it with `hard=True` but no dice there, either. Maybe the issue is related to another cache (if exists) or to the function being passed to serialise? Apparently, it's the `commands` part that it gets hung up on.

In a couple tests, I was able to get it to work by excluding build_command or commands but when both are present, it fails with the error above. Not sure why though.

**Comment by ColinKennedy** [comment]
I managed to get the package to write using this code

```python
from rez.utils.filesystem import make_path_writable
from rez.serialise import open_file_for_write
import stat

with make_path_writable(os.path.dirname(os.path.dirname(package.filepath))):
    with open_file_for_write(package.filepath, mode=(stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH)) as f:
        f.write(
            textwrap.dedent(
                """\
                # -*- coding: utf-8 -*-

                name = "foo_bar"

                requires = ["something"]

                version = "1.2.0"

                build_command = "echo 'asdf'"

                def commands():
                    pass
                """
            )
        )

package = packages_.get_developer_package(path)
package.version  # <-- is now 1.2.0

```

If that's the intended way for modifying DeveloperPackage objects then I'll keep using that. But if it's a bug and `get_developer_package` function should work without it then I hope this serves as a repro :).

**Comment by nerdvegas** [comment]
Hey Colin, this is a bug for sure. You should be able to load a dev pkg
after modification, in fact dev packages shouldn't be ending up in the
cache at all.

Thx
A
