### ISSUE TITLE
rez-pip cannot install astroid 2.2.0 for Python 3.6

### ISSUE THREAD

**Issue by ColinKennedy** [nerdvegas/rez#876]
I tried installing astroid 2.2.0, which is a dependency of pylint

```
$ rez-pip --install astroid==2.2.0 --python-version=3.6                                                                                                 
07:24:47 INFO     Trying to use pip from python package
07:24:47 INFO     Found pip-20.0.2 inside /home/selecaoone/packages/python/3.6.8/package.py. Will use it with /usr/bin/python3                                                                      
07:24:47 INFO     Installing 'astroid==2.2.0' with pip taken from '/usr/bin/python3'
Collecting astroid==2.2.0
  Using cached https://files.pythonhosted.org/packages/31/e9/610c16ecc417c1918915f8f30e54fcfd195788fe450cf8d7d1a061e14628/astroid-2.2.0-py3-none-any.whl                                            
Collecting six (from astroid==2.2.0)
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl                                           
Collecting lazy-object-proxy (from astroid==2.2.0)
  Using cached https://files.pythonhosted.org/packages/0b/dd/b1e3407e9e6913cf178e506cd0dee818e58694d9a5cd1984e3f6a8b9a10f/lazy_object_proxy-1.4.3-cp36-cp36m-manylinux1_x86_64.whl                  
Collecting typed-ast<1.3.0; python_version < "3.7" and implementation_name == "cpython" (from astroid==2.2.0)                                                                                       
  Using cached https://files.pythonhosted.org/packages/52/6c/57ecbb2ecb80274b7f2b7f95d0937de310aa2e66839d7ae9436881525b23/typed_ast-1.2.0-cp36-cp36m-manylinux1_x86_64.whl                          
Collecting wrapt (from astroid==2.2.0)
Installing collected packages: six, lazy-object-proxy, typed-ast, wrapt, astroid
Successfully installed astroid-2.2.0 lazy-object-proxy-1.4.3 six-1.14.0 typed-ast-1.2.0 wrapt-1.12.1                                                                                                
WARNING: You are using pip version 19.1.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/home/selecaoone/rez-python-3.6/lib/python3.6/site-packages/rez/vendor/distlib/metadata.py", line 732, in __init__                                                                          
    self._data = json.loads(data)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/selecaoone/rez-python-3.6/bin/rez/rez-pip", line 8, in <module>
    sys.exit(run_rez_pip())
  File "/home/selecaoone/rez-python-3.6/lib/python3.6/site-packages/rez/cli/_entry_points.py", line 187, in run_rez_pip                                                                             
    return run("pip")
  File "/home/selecaoone/rez-python-3.6/lib/python3.6/site-packages/rez/cli/_main.py", line 152, in run                                                                                             
    returncode = run_cmd()
  File "/home/selecaoone/rez-python-3.6/lib/python3.6/site-packages/rez/cli/_main.py", line 144, in run_cmd                                                                                         
    return opts.func(opts, opts.parser, extra_arg_groups)
  File "/home/selecaoone/rez-python-3.6/lib/python3.6/site-packages/rez/cli/pip.py", line 67, in command                                                                                            
    extra_args=opts.extra)
  File "/home/selecaoone/rez-python-3.6/lib/python3.6/site-packages/rez/pip.py", line 289, in pip_install_package                                                                                   
    distributions = list(distribution_path.get_distributions())
  File "/home/selecaoone/rez-python-3.6/lib/python3.6/site-packages/rez/vendor/distlib/database.py", line 213, in get_distributions                                                                 
    self._generate_cache()
  File "/home/selecaoone/rez-python-3.6/lib/python3.6/site-packages/rez/vendor/distlib/database.py", line 167, in _generate_cache                                                                   
    for dist in self._yield_distributions():
  File "/home/selecaoone/rez-python-3.6/lib/python3.6/site-packages/rez/vendor/distlib/database.py", line 148, in _yield_distributions                                                              
    metadata = Metadata(fileobj=stream, scheme='legacy')
  File "/home/selecaoone/rez-python-3.6/lib/python3.6/site-packages/rez/vendor/distlib/metadata.py", line 742, in __init__                                                                          
    scheme=scheme)
  File "/home/selecaoone/rez-python-3.6/lib/python3.6/site-packages/rez/vendor/distlib/metadata.py", line 285, in __init__                                                                          
    self.read_file(fileobj)
  File "/home/selecaoone/rez-python-3.6/lib/python3.6/site-packages/rez/vendor/distlib/metadata.py", line 383, in read_file                                                                         
    self.set(field, value)
  File "/home/selecaoone/rez-python-3.6/lib/python3.6/site-packages/rez/vendor/distlib/metadata.py", line 478, in set                                                                               
    if not scheme.is_valid_constraint_list(value):
  File "/home/selecaoone/rez-python-3.6/lib/python3.6/site-packages/rez/vendor/distlib/version.py", line 713, in is_valid_constraint_list                                                           
    return self.is_valid_matcher('dummy_name (%s)' % s)
  File "/home/selecaoone/rez-python-3.6/lib/python3.6/site-packages/rez/vendor/distlib/version.py", line 703, in is_valid_matcher                                                                   
    self.matcher(s)
  File "/home/selecaoone/rez-python-3.6/lib/python3.6/site-packages/rez/vendor/distlib/version.py", line 116, in __init__                                                                           
    '%r constraints' % op)
ValueError: '.*' not allowed for '>=' constraints
```

astroid 2.2.0 fails but `rez-pip --install astroid==2.1.0 --python-version=3.6` does work. So there may be some change between astroid version 2.1.0 and 2.2.0 which rez-pip does not currently support.

rez: 2.56.1 (tried with both a Python 3.6 and 2.7 install of Rez both fail with the same error)
python: 3.6 / 2.7
os: CentOS-7.7.1908

**Comment by ColinKennedy** [comment]
## Summary
Looks like a problem with astroid itself. I'll take it up with their maintainers

## Details
Tracking this down a bit. The issue comes from astroid (not any of its dependencies)

Here's a copy of its metadata

```
Metadata-Version: 2.1
Name: astroid
Version: 2.2.0
Summary: An abstract syntax tree for Python with inference support.
Home-page: https://github.com/PyCQA/astroid
Author: Python Code Quality Authority
Author-email: code-quality@python.org
License: LGPL
Platform: UNKNOWN
Classifier: Topic :: Software Development :: Libraries :: Python Modules
Classifier: Topic :: Software Development :: Quality Assurance
Classifier: Programming Language :: Python
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.4
Classifier: Programming Language :: Python :: 3.5
Classifier: Programming Language :: Python :: 3.6
Classifier: Programming Language :: Python :: 3.7
Classifier: Programming Language :: Python :: Implementation :: CPython
Classifier: Programming Language :: Python :: Implementation :: PyPy
Requires-Python: >=3.4.*
Requires-Dist: lazy-object-proxy
Requires-Dist: six
Requires-Dist: wrapt
Requires-Dist: typing; python_version < "3.5"
Requires-Dist: typed-ast (<1.3.0); python_version < "3.7" and implementation_name == "cpython"
Requires-Dist: typed-ast (>=1.3.0); python_version >= "3.7" and implementation_name == "cpython"

Astroid
=======

.. image:: https://travis-ci.org/PyCQA/astroid.svg?branch=master
    :target: https://travis-ci.org/PyCQA/astroid

.. image:: https://ci.appveyor.com/api/projects/status/co3u42kunguhbh6l/branch/master?svg=true
    :alt: AppVeyor Build Status
    :target: https://ci.appveyor.com/project/PCManticore/astroid

.. image:: https://coveralls.io/repos/github/PyCQA/astroid/badge.svg?branch=master
    :target: https://coveralls.io/github/PyCQA/astroid?branch=master

.. image:: https://readthedocs.org/projects/astroid/badge/?version=latest
    :target: http://astroid.readthedocs.io/en/latest/?badge=latest
    :alt: Documentation Status

.. image:: https://img.shields.io/badge/code%20style-black-000000.svg
    :target: https://github.com/ambv/black



What's this?
------------

The aim of this module is to provide a common base representation of
python source code. It is currently the library powering pylint's capabilities.

It provides a compatible representation which comes from the `_ast`
module.  It rebuilds the tree generated by the builtin _ast module by
recursively walking down the AST and building an extended ast. The new
node classes have additional methods and attributes for different
usages. They include some support for static inference and local name
scopes. Furthermore, astroid can also build partial trees by inspecting living
objects.


Installation
------------

Extract the tarball, jump into the created directory and run::

	pip install .


If you want to do an editable installation, you can run::

    pip install -e .


If you have any questions, please mail the code-quality@python.org
mailing list for support. See
http://mail.python.org/mailman/listinfo/code-quality for subscription
information and archives.

Documentation
-------------
http://astroid.readthedocs.io/en/latest/


Python Versions
---------------

astroid 2.0 is currently available for Python 3 only. If you want Python 2
support, older versions of astroid will still supported until 2020.

Test
----

Tests are in the 'test' subdirectory. To launch the whole tests suite, you can use
either `tox` or `pytest`::

  tox
  pytest astroid
```

Specifically this line `Requires-Python: >=3.4.*`
It looks like the error happens because there's `>=` and `.*` in the same expression.

Then checking out `setup.py` in astroid 2.2.0, it's clearly visible here

```python
def install():
    return setup(name = distname,
                 # ...
                 python_requires='>=3.4.*',
                 # ...
                 )
```

I know nothing about distlib / setup.py beyond the basics but it looks like [PEP-440](https://www.python.org/dev/peps/pep-0440/#id54) doesn't support this syntax.
