### ISSUE TITLE
Resolve conflict issue (package-cache branch)

### ISSUE THREAD

**Issue by seymour88** [nerdvegas/rez#896]
While testing the package-cache branch I've hit an issue when a resolve conflict occurs.
If I run a rez-env specifying two conflicting versions of a package I get the following stacktrace:
```
Traceback (most recent call last):
  File "/library/rez/user_packages/rez-pre-release/rez/2.61.0.pr/os-CentOS-7/python-2.7/bin/rez/rez", line 8, in <module>
    sys.exit(run_rez())
  File "/library/rez/user_packages/rez-pre-release/rez/2.61.0.pr/os-CentOS-7/python-2.7/lib/python2.7/site-packages/rez/cli/_entry_points.py", line 64, in run_rez
    return run()
  File "/library/rez/user_packages/rez-pre-release/rez/2.61.0.pr/os-CentOS-7/python-2.7/lib/python2.7/site-packages/rez/cli/_main.py", line 160, in run
    returncode = run_cmd()
  File "/library/rez/user_packages/rez-pre-release/rez/2.61.0.pr/os-CentOS-7/python-2.7/lib/python2.7/site-packages/rez/cli/_main.py", line 152, in run_cmd
    return func(opts, opts.parser, extra_arg_groups)
  File "/library/rez/user_packages/rez-pre-release/rez/2.61.0.pr/os-CentOS-7/python-2.7/lib/python2.7/site-packages/rez/cli/env.py", line 211, in command
    package_caching=(not opts.no_pkg_cache)
File "/library/rez/user_packages/rez-pre-release/rez/2.61.0.pr/os-CentOS-7/python-2.7/lib/python2.7/site-packages/rez/resolved_context.py", line 316, in __init__
    self._update_package_cache()
  File "/library/rez/user_packages/rez-pre-release/rez/2.61.0.pr/os-CentOS-7/python-2.7/lib/python2.7/site-packages/rez/resolved_context.py", line 1572, in _update_package_cache
    pkgcache.add_variants_async(self.resolved_packages)
  File "/library/rez/user_packages/rez-pre-release/rez/2.61.0.pr/os-CentOS-7/python-2.7/lib/python2.7/site-packages/rez/package_cache.py", line 379, in add_variants_async
    for variant in variants:
TypeError: 'NoneType' object is not iterable
```

**Comment by nerdvegas** [comment]
Dup of https://github.com/nerdvegas/rez/issues/905
